import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  modulesSidebar: [
    {
      type: 'category',
      label: 'Modules',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Module 1: ROS 2',
          items: [
            {
              type: 'autogenerated',
              dirName: 'modules/module-1-ros2',
            },
          ],
        },
        {
          type: 'category',
          label: 'Module 2: Gazebo & Unity',
          items: [
            {
              type: 'autogenerated',
              dirName: 'modules/module-2-gazebo-unity',
            },
          ],
        },
        {
          type: 'category',
          label: 'Module 3: NVIDIA Isaac',
          items: [
            {
              type: 'autogenerated',
              dirName: 'modules/module-3-isaac',
            },
          ],
        },
        {
          type: 'category',
          label: 'Module 4: VLA Models',
          items: [
            {
              type: 'autogenerated',
              dirName: 'modules/module-4-vla',
            },
          ],
        },
      ],
    },
  ],
  weeksSidebar: [
    {
      type: 'category',
      label: 'Weekly Schedule',
      items: [
        {
          type: 'autogenerated',
          dirName: 'weeks',
        },
      ],
    },
  ],
  hardwareSidebar: [
    {
      type: 'category',
      label: 'Hardware Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'hardware',
        },
      ],
    },
  ],
};

export default sidebars;